[package]
name = "horaires"
version = "0.1.0"
authors = ["Xavier Gillard <xavier.gillard@uclouvain.be>"]

[dependencies]
clap           = "2.32.0"
dotenv         = "0.13.0"
dotenv_codegen = "0.11.0"
webbrowser     = "0.3.1"


[profile.release]
lto = true